services:
  heading: "Servicios"
  subheading: "Los servicios que ofrezco"
  items:
    - title: "Mi Blog"
      icon: "blog.png"
      link: "https://isaacrd.github.io/"
      link_target: "_blank"
      alt: "img blog"
      description: "Un blog donde publico mis guías de distinta índole, en el marco de la ciberseguridad"
    - title: "Ingeniería"
      icon: "ingenieria.png"
      alt: "img ingeniería"
      description: "Como licenciado en Ingeniería, estoy capacitado para llevar a cabo proyectos, su documentación, gráficos UML, etc."
    - title: "Ciberseguridad"
      icon: "ciberseguridad.png"
      alt: "img ciberseguridad"
      description: "Mi área de especialización es la ciberseguridad, concretamente el equipo Red Team, Pentester. Estoy capacitado en múltiples herramientas y sigo capacitándome constantemente."
    - title: "Informes"
      icon: "informe.png"
      alt: "img informe"
      description: "Elaboración de informes de auditorías a clientes, que buscan constantemente mantener sus servicios seguros ante ataques cibernéticos."
    - title: "Informes automatizados"
      icon: "informeautomatico.png"
      alt: "img informes automatizados"
      description: "Elaboración de informes automatizados para clientes que necesitan llevar un control exhaustivo de sus datos."
    - title: "Desarrollo web WordPress"
      icon: "desarrollo-web.png"
      alt: "img desarrollo-web"
      description: "Creación de páginas web con WordPress, utilizando múltiples herramientas que ofrecen una excelente experiencia para sus clientes."

about:
  heading: "Mi trayectoria"
  timeline:
    - period: "2020-2024"
      title: "Universidad Andrés Bello"
      image: "unab.jpg"
      text: "En el año 2020 ingresé a la Universidad Andrés Bello, la cual me nutrió de nuevos y desafiantes conocimientos respecto a la informática e ingeniería, los cuales finalicé en el año 2024."
    - period: "2023"
      title: "Municipalidad de Peñaflor"
      image: "penaflor.jpg"
      inverted: true
      text: "En el año 2023 trabajé en la Municipalidad de Peñaflor, donde llevé a cabo numerosos proyectos, recibí excelentes calificaciones por parte de mis colegas y obtuve una carta de recomendación del director del área."
    - period: "Enero 2024"
      title: "Ciberseguridad"
      image: "trabajo.jpg"
      text: "Realicé diferentes cursos de Ciberseguridad, en el área de Pentesting, obteniendo certificados y sólidas bases cibernéticas. Tengo como meta obtener a corto y mediano plazo las certificaciones eJPT y eWPT."
    - period: "2024 ~ 2025"
      title: "Inserción laboral"
      image: "trabajo.jpg"
      inverted: true
      text: "Actualmente estoy buscando nuevas oportunidades para llenarme de nuevos conocimientos y alcanzar la excelencia. Si estás interesado en trabajar conmigo, ¡comunícate conmigo!"
  cta:
    line1: "¡Se parte"
    line2: "de nuestra"
    line3: "Historia!"
